name: "Flinter.md"
icon: "align-justify"
color: "red"
description: "A customizable Markdown Frontmatter linter"
author: "JackDevAU"

inputs:
  GITHUB_TOKEN:
    description: "GitHub token"
    required: true

runs:
  using: "node16"
  main: "dist/index.js"
